In [1]:
pwd

'C:\\Users\\human\\Desktop\\수업자료\\데이터분석&시각화\\텍스트마이닝\\06 _TF_IDF\\TF_IDF(1)'

In [2]:
import pandas as pd
from konlpy.tag import Okt
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

In [35]:
df=pd.read_csv('./data/전처리_샘플뉴스.csv')
df

,title,text,url,media,date
0,방역 2.5단계 뒤 을씨년스럽게 변한 '스벅'···별천지된 '파바',서울의 밤이 달라졌다. 수도권을 대상으로 이른바 ‘사회적 거리두기 2.5단계’가 시...,https://news.naver.com/main/read.nhn?mode=LPOD...,중앙일보,2020-08-31
1,"""기적 같은 선방""이라지만...현장은 성한 곳이 없다","“50년 동안 사업하면서 소위 ‘깡통’을 세 번 차고도 재기했는데, 이번 위기는 정...",https://news.naver.com/main/read.nhn?mode=LPOD...,한국일보,2020-08-03
2,13일까지 장맛비… 사흘간 물폭탄 사망·실종 25명,곳곳 수해 초비상 \r\n\r\n 3일 오전 충남 천안과 아산지역에 호우경보가...,https://news.naver.com/main/read.nhn?mode=LPOD...,세계일보,2020-08-04
3,최악 장마에 태풍까지… 내일까지 최고 300㎜,예측하기 어려운 ‘물폭탄’을 동반한 장마가 유례없이 길어지고 있다. 설상가상으로 9...,https://news.naver.com/main/read.nhn?mode=LPOD...,국민일보,2020-08-10
4,은행 예금금리 사상 첫 0%대,대출금리도 2.72% 사상최저\r\n\r\n\r\n\r\n\t\t\t\t은행 예금에...,https://news.naver.com/main/read.nhn?mode=LPOD...,조선일보,2020-08-01

In [10]:
text_res=[]
for i in df['text']:
    text_res.extend(i.split('\n'))
    break
text_res

['서울의 밤이 달라졌다. 수도권을 대상으로 이른바 ‘사회적 거리두기 2.5단계’가 시행되면서 음식점 등이 오후 9시에 대거 문을 닫았기 때문이다.  \r',
 ' \r',
 '   2.5단계 시행 첫날인 이날 서울 중심가의 식당과 술집 등은 매장 내 취식 금지 시작 시각인 오후 9시를 전후로 속속 장사를 접었다. 한식집 등 식사 위주의 식당은 해가 지면서 일찌감치 마감했고, 고깃집이나 횟집·이자카야·맥줏집 등도 ‘데드라인’이 임박하자 손님을 내보내고 매장을 정리하기 시작했다. 평소라면 간판 불빛으로 불야성이었을 번화가 골목들이 깜깜해질 정도였다.  \r',
 ' \r',
 '   서울 종각역 인근 맥줏집 사장 김모(30)씨는 오후 8시50분이 되자 손님들에게 “오후 9시 마감이니 나가 달라”고 부탁했다. 이 가게의 평소 영업시간은 오후 5시부터 다음 날 오전 2시까지였다. 김씨는 “원래 가장 붐비는 시간인데 문을 닫아야 한다. 코로나19 때문에 매출액이 예년의 4분의 1로 줄었는데 이젠 그 반토막도 안 될 것 같다”고 한숨을 내쉬었다.  \r',
 ' \r',
 '              오후 9시쯤 한 식당에서 나온 최모(22)씨는 “친구들과의 약속 때문에 나왔는데 강제로 이 시간에 귀가해야 한다니 아쉽다”고 말했다. 4층 규모의 한 대형 술집은 ‘2.5단계’가 시행되는 다음 달 6일까지 아예 문을 닫기로 했다. 이 술집 사장은 “오후 9시까지만 영업하라는 건 그냥 술집 문을 닫으라는 이야기”라며 “포장, 배달은 가능하다지만 누가 술집에서 술이나 안주를 배달시켜 먹겠나”라고 말했다. 서울역 대합실 내 한식당 등도 오후 9시 이전에 문을 닫았다. 패스트푸드 가게도 일부 포장 주문 손님만 눈에 보일 뿐 한산했다.  \r',
 ' \r',
 '   서울 중구의 한 순댓국집 사장 홍정복(60)씨는 “원래 오후 9시에서 오전 1시 사이의 매출이 전체의 30%를 차지한다”며 “매출액이 줄어 아쉽지만, 많이들 동참해 최대한 빨리 코로나19가 잠잠해지길 바란다”고 말했다.  \r',
 ' \r',
 '   업종별로 희비가 갈리기도 했다. 온종일 포장·배달 판매만 가능한 프랜차이즈 커피전문점은 썰렁한 모습이었다.  \r',
 ' \r',
 ' 결혼식 온라인 생중계, 축하는 댓글로 축의금은 계좌이체  \r',
 ' \r',
 '              30일 오후 1시 ‘정자동 카페거리’로 불리는 경기도 성남시 분당구 정자동 카페 밀집지역의 스타벅스에서는 고객을 찾아보기 어려웠다. 어쩌다 찾은 고객도 발길을 돌리기 일쑤였다. 매장 직원은 “포장 판매만 가능하다는 설명을 듣고 발길을 돌린 고객이 10명 이상이다. 화를 낸 고객도 있었다”며 한숨을 내쉬었다.  \r',
 ' \r',
 '   하지만 이곳에서 불과 180m 떨어진 파리바게뜨는 별천지였다. 4인석 테이블 10개 중 8개에 손님이 앉아 있었다. 이들은 가족·지인과 모여 앉아 커피를 마시거나 빵을 먹었다. 노트북 컴퓨터를 이용해 개인업무를 보는 이도 있었다. 제과점은 음식점과 마찬가지로 오전 5시부터 오후 9시까지는 현장 취식이 가능하기 때문이다. 또 다른 ‘무풍지대’인 비(非)프랜차이즈형 소규모 개인카페도 고객으로 북적였다. 소셜네트워크서비스(SNS)에서 인기를 끌고 있는 경기도 광주시의 한 카페는 낮 12시에 이미 12대를 수용할 수 있는 1층 주차장이 만차 상태였다.  \r',
 ' \r',
 '   프랜차이즈 커피전문점 중에서도 차 안에서 음료를 받는 드라이브 스루(Drive-thru) 방식의 매장은 현장 취식 금지 대상이 아니라 고객 발길이 이어졌다. 낮 12시30분쯤 경기도 남양주시의 한 스타벅스 드라이브 스루 점포로 들어서는 차로에는 차량 14대가 줄줄이 늘어서 있었다. 송파나루역 인근 매장에서도 고객이 몰리면서 차량이 70~80m나 줄을 서는 바람에 교통체증이 빚어졌다. 한 프렌차이즈 커피전문점 관계자는 “똑같이 빵과 커피를 파는데 우리는 안 되고, 제과점은 된다는 게 말이 되느냐”고 불만을 토로하기도 했다.  \r',
 ' \r',
 '   방역 강화로 50명 이상 규모의 현장 결혼식이 원천 봉쇄되면서 ‘온라인 결혼식’으로 방향을 선회한 부부도 늘고 있다. 예식을 한 차례 연기했던 신준하(37)·김지현(33) 부부는 최근 코로나19가 재확산하자 ‘오프라인 결혼식’을 포기하고 온라인 결혼식을 올렸다. 이들은 모바일 청첩장에 결혼식 영상 중계 홈페이지 주소를 첨부해 지인들에게 보냈다.  \r',
 ' \r',
 '   29일 오후 2시30분부터 생중계된 이들의 결혼식을 90명에 가까운 ‘온라인 하객’이 지켜봤다. 신부 아버지가 직접 축가를 하자 “아버님의 축가가 너무 멋지네요”라는 댓글이 달리기도 했다. 신씨는 “이번 사태를 계기로 결혼식 문화가 바뀔 수 있겠다는 생각도 든다”고 말했다. 22일 대만 여성과 한국에서 결혼식을 올린 김모(33)씨도 온라인 생중계를 했다. 코로나19 재확산으로 대만에 있는 신부 부모가 참석하지 못했기 때문이다.  \r',
 ' \r',
 '   온라인 결혼식 중계를 하는 이준희 가빈컴퍼니 대표는 “‘온라인 하객’은 계좌번호를 링크 형태로 전달받아 축의금을 보낼 수 있고, 혼주 쪽에서는 하객이 입력한 주소와 전화번호를 이용해 답례품을 보낼 수 있다”며 “지난 18일 하객 수 제한 조처 이후 300건이 넘는 문의가 쏟아졌다”고 말했다. 한편 질병관리본부 중앙방역대책본부(방대본)에 따르면 30일 0시 기준 전국의 코로나19 환자는 하루 동안 299명 늘어 지난 25일(280명) 이후 닷새 만에 300명 아래로 떨어졌다. 정은경 방대본부장은 “코로나19가 최후의 방어선이라 생각한 의료기관과 요양시설로까지 확산 중이며 역학조사 여력도 한계에 다다른 상황”이라며 “코로나19를 다시 통제 가능한 수준으로 줄일 수 있을지 판가름할 중요한 시기인 만큼 거리두기를 철저히 이행해 달라”고 말했다.  \r',
 ' \r',
 '   정진호·채혜선·권혜림·백민정 기자 jeong.jinho@joongang.co.kr  \r',
 '\r',
 '\r',
 '▶ \r',
 '▶ \r',
 '▶ \r',
 '\r',
 'ⓒ중앙일보(https://joongang.co.kr), 무단 전재 및 재배포 금지']

In [7]:
df['text'][0]

'서울의 밤이 달라졌다. 수도권을 대상으로 이른바 ‘사회적 거리두기 2.5단계’가 시행되면서 음식점 등이 오후 9시에 대거 문을 닫았기 때문이다.  \r\n \r\n   2.5단계 시행 첫날인 이날 서울 중심가의 식당과 술집 등은 매장 내 취식 금지 시작 시각인 오후 9시를 전후로 속속 장사를 접었다. 한식집 등 식사 위주의 식당은 해가 지면서 일찌감치 마감했고, 고깃집이나 횟집·이자카야·맥줏집 등도 ‘데드라인’이 임박하자 손님을 내보내고 매장을 정리하기 시작했다. 평소라면 간판 불빛으로 불야성이었을 번화가 골목들이 깜깜해질 정도였다.  \r\n \r\n   서울 종각역 인근 맥줏집 사장 김모(30)씨는 오후 8시50분이 되자 손님들에게 “오후 9시 마감이니 나가 달라”고 부탁했다. 이 가게의 평소 영업시간은 오후 5시부터 다음 날 오전 2시까지였다. 김씨는 “원래 가장 붐비는 시간인데 문을 닫아야 한다. 코로나19 때문에 매출액이 예년의 4분의 1로 줄었는데 이젠 그 반토막도 안 될 것 같다”고 한숨을 내쉬었다.  \r\n \r\n              오후 9시쯤 한 식당에서 나온 최모(22)씨는 “친구들과의 약속 때문에 나왔는데 강제로 이 시간에 귀가해야 한다니 아쉽다”고 말했다. 4층 규모의 한 대형 술집은 ‘2.5단계’가 시행되는 다음 달 6일까지 아예 문을 닫기로 했다. 이 술집 사장은 “오후 9시까지만 영업하라는 건 그냥 술집 문을 닫으라는 이야기”라며 “포장, 배달은 가능하다지만 누가 술집에서 술이나 안주를 배달시켜 먹겠나”라고 말했다. 서울역 대합실 내 한식당 등도 오후 9시 이전에 문을 닫았다. 패스트푸드 가게도 일부 포장 주문 손님만 눈에 보일 뿐 한산했다.  \r\n \r\n   서울 중구의 한 순댓국집 사장 홍정복(60)씨는 “원래 오후 9시에서 오전 1시 사이의 매출이 전체의 30%를 차지한다”며 “매출액이 줄어 아쉽지만, 많이들 동참해 최대한 빨리 코로나19가 잠잠해지길 바란다”고 말했다.  \r\n \r\n   업종별로 희비가 갈리기도 했다. 온종일 포장·배달 판매만 가능한 프랜차이즈 커피전문점은 썰렁한 모습이었다.  \r\n \r\n 결혼식 온라인 생중계, 축하는 댓글로 축의금은 계좌이체  \r\n \r\n              30일 오후 1시 ‘정자동 카페거리’로 불리는 경기도 성남시 분당구 정자동 카페 밀집지역의 스타벅스에서는 고객을 찾아보기 어려웠다. 어쩌다 찾은 고객도 발길을 돌리기 일쑤였다. 매장 직원은 “포장 판매만 가능하다는 설명을 듣고 발길을 돌린 고객이 10명 이상이다. 화를 낸 고객도 있었다”며 한숨을 내쉬었다.  \r\n \r\n   하지만 이곳에서 불과 180m 떨어진 파리바게뜨는 별천지였다. 4인석 테이블 10개 중 8개에 손님이 앉아 있었다. 이들은 가족·지인과 모여 앉아 커피를 마시거나 빵을 먹었다. 노트북 컴퓨터를 이용해 개인업무를 보는 이도 있었다. 제과점은 음식점과 마찬가지로 오전 5시부터 오후 9시까지는 현장 취식이 가능하기 때문이다. 또 다른 ‘무풍지대’인 비(非)프랜차이즈형 소규모 개인카페도 고객으로 북적였다. 소셜네트워크서비스(SNS)에서 인기를 끌고 있는 경기도 광주시의 한 카페는 낮 12시에 이미 12대를 수용할 수 있는 1층 주차장이 만차 상태였다.  \r\n \r\n   프랜차이즈 커피전문점 중에서도 차 안에서 음료를 받는 드라이브 스루(Drive-thru) 방식의 매장은 현장 취식 금지 대상이 아니라 고객 발길이 이어졌다. 낮 12시30분쯤 경기도 남양주시의 한 스타벅스 드라이브 스루 점포로 들어서는 차로에는 차량 14대가 줄줄이 늘어서 있었다. 송파나루역 인근 매장에서도 고객이 몰리면서 차량이 70~80m나 줄을 서는 바람에 교통체증이 빚어졌다. 한 프렌차이즈 커피전문점 관계자는 “똑같이 빵과 커피를 파는데 우리는 안 되고, 제과점은 된다는 게 말이 되느냐”고 불만을 토로하기도 했다.  \r\n \r\n   방역 강화로 50명 이상 규모의 현장 결혼식이 원천 봉쇄되면서 ‘온라인 결혼식’으로 방향을 선회한 부부도 늘고 있다. 예식을 한 차례 연기했던 신준하(37)·김지현(33) 부부는 최근 코로나19가 재확산하자 ‘오프라인 결혼식’을 포기하고 온라인 결혼식을 올렸다. 이들은 모바일 청첩장에 결혼식 영상 중계 홈페이지 주소를 첨부해 지인들에게 보냈다.  \r\n \r\n   29일 오후 2시30분부터 생중계된 이들의 결혼식을 90명에 가까운 ‘온라인 하객’이 지켜봤다. 신부 아버지가 직접 축가를 하자 “아버님의 축가가 너무 멋지네요”라는 댓글이 달리기도 했다. 신씨는 “이번 사태를 계기로 결혼식 문화가 바뀔 수 있겠다는 생각도 든다”고 말했다. 22일 대만 여성과 한국에서 결혼식을 올린 김모(33)씨도 온라인 생중계를 했다. 코로나19 재확산으로 대만에 있는 신부 부모가 참석하지 못했기 때문이다.  \r\n \r\n   온라인 결혼식 중계를 하는 이준희 가빈컴퍼니 대표는 “‘온라인 하객’은 계좌번호를 링크 형태로 전달받아 축의금을 보낼 수 있고, 혼주 쪽에서는 하객이 입력한 주소와 전화번호를 이용해 답례품을 보낼 수 있다”며 “지난 18일 하객 수 제한 조처 이후 300건이 넘는 문의가 쏟아졌다”고 말했다. 한편 질병관리본부 중앙방역대책본부(방대본)에 따르면 30일 0시 기준 전국의 코로나19 환자는 하루 동안 299명 늘어 지난 25일(280명) 이후 닷새 만에 300명 아래로 떨어졌다. 정은경 방대본부장은 “코로나19가 최후의 방어선이라 생각한 의료기관과 요양시설로까지 확산 중이며 역학조사 여력도 한계에 다다른 상황”이라며 “코로나19를 다시 통제 가능한 수준으로 줄일 수 있을지 판가름할 중요한 시기인 만큼 거리두기를 철저히 이행해 달라”고 말했다.  \r\n \r\n   정진호·채혜선·권혜림·백민정 기자 jeong.jinho@joongang.co.kr  \r\n\r\n\r\n▶ \r\n▶ \r\n▶ \r\n\r\nⓒ중앙일보(https://joongang.co.kr), 무단 전재 및 재배포 금지'

In [14]:
# 문자별 명사 추출
okt=Okt()
nouns=[okt.nouns(i) for i in text_res]

In [20]:
len(nouns)

34

In [21]:
# stop_word
stop_word=['서울','단계']
last_nouns=[]
for i in nouns:
    last_nouns.append([j for j in i if j not in stop_word])

last_nouns

[['밤', '수도권', '대상', '사회', '거리', '두기', '시행', '음식점', '등', '오후', '대거', '문', '때문'],
 [],
 ['시행',
  '첫날',
  '날',
  '중심',
  '가의',
  '식당',
  '술집',
  '등',
  '매장',
  '내',
  '취식',
  '금지',
  '시작',
  '시각',
  '오후',
  '전후',
  '장사',
  '한식',
  '집',
  '등',
  '식사',
  '위주',
  '식당',
  '해',
  '지면',
  '찌',
  '감치',
  '마감',
  '고깃집',
  '횟집',
  '이자카야',
  '맥줏집',
  '등',
  '데드라인',
  '이',
  '임박',
  '손님',
  '매장',
  '정리',
  '시작',
  '평소',
  '라면',
  '간판',
  '불빛',
  '불야성',
  '번화가',
  '골목',
  '깜깜',
  '정도'],
 [],
 ['종각역',
  '인근',
  '맥줏집',
  '사장',
  '김모',
  '씨',
  '오후',
  '손님',
  '오후',
  '마감',
  '달라',
  '고',
  '부탁',
  '이',
  '가게',
  '평소',
  '영업',
  '시간',
  '오후',
  '다음',
  '날',
  '오전',
  '김씨',
  '원래',
  '가장',
  '시간',
  '문',
  '코로나',
  '때문',
  '매출',
  '액',
  '예년',
  '로',
  '젠',
  '그',
  '반토막',
  '안',
  '것',
  '고',
  '한숨'],
 [],
 ['오후',
  '식당',
  '최모',
  '씨',
  '친구',
  '약속',
  '때문',
  '강제',
  '이',
  '시간',
  '귀가',
  '고',
  '말',
  '층',
  '규모',
  '대형',
  '술집',
  '시행',
  '다음',
  '달',
  '아예',
  '문',
  '이',
  '술집',
  '사장',
  '오후',
  '영업',
  '건',
  '그냥',
  '술집',
  '문',
  '이야기',
  '라며',
  '포장',
  '배달',
  '누가',
  '술집',
  '술',
  '안주',
  '배달',
  '말',
  '서울역',
  '대합실',
  '내',
  '한식당',
  '등',
  '오후',
  '이전',
  '문',
  '패스트푸드',
  '가게',
  '일부',
  '포장',
  '주문',
  '손님',
  '눈',
  '뿐'],
 [],
 ['중구',
  '국집',
  '사장',
  '홍',
  '정복',
  '씨',
  '원래',
  '오후',
  '오전',
  '사이',
  '매출',
  '전체',
  '를',
  '차지',
  '며',
  '매출',
  '액',
  '동참',
  '최대한',
  '코로나',
  '고',
  '말'],
 [],
 ['업종',
  '별로',
  '희비',
  '갈리',
  '기도',
  '온종일',
  '포장',
  '배달',
  '판매',
  '프랜차이즈',
  '커피전문점',
  '모습'],
 [],
 ['결혼식', '온라인', '생중계', '축하', '댓글', '축의금', '계좌', '이체'],
 [],
 ['오후',
  '정자동',
  '카페',
  '거리',
  '로',
  '경기도',
  '성남시',
  '분당구',
  '정자동',
  '카페',
  '밀집',
  '지역',
  '스타벅스',
  '고객',
  '고객',
  '발길',
  '일쑤',
  '매장',
  '직원',
  '포장',
  '판매',
  '설명',
  '발길',
  '고객',
  '명',
  '이상',
  '화',
  '고객',
  '며',
  '한숨'],
 [],
 ['곳',
  '불과',
  '파리',
  '바게뜨',
  '별천지',
  '인석',
  '테이블',
  '개',
  '중',
  '개',
  '손님',
  '이',
  '가족',
  '지인',
  '커피',
  '빵',
  '노트북',
  '컴퓨터',
  '이용',
  '개인',
  '업무',
  '이도',
  '제과점',
  '음식점',
  '마찬가지',
  '오전',
  '오후',
  '현장',
  '취식',
  '때문',
  '또',
  '다른',
  '무풍지대',
  '인',
  '비',
  '프랜차이즈',
  '소규모',
  '개인',
  '카페',
  '고객',
  '북적',
  '소셜네트워크서비스',
  '인기',
  '끌',
  '경기도',
  '광주시',
  '카페',
  '낮',
  '수용',
  '수',
  '층',
  '주차장',
  '차',
  '상태'],
 [],
 ['프랜차이즈',
  '커피전문점',
  '중',
  '차',
  '안',
  '음료',
  '드라이브',
  '스루',
  '방식',
  '매장',
  '현장',
  '취식',
  '금지',
  '대상',
  '고객',
  '발길',
  '낮',
  '경기도',
  '남양주시',
  '스타벅스',
  '드라이브',
  '스루',
  '점포',
  '차로',
  '차량',
  '대가',
  '줄줄이',
  '송파',
  '나루',
  '역',
  '인근',
  '매장',
  '고객',
  '차량',
  '나',
  '줄',
  '바람',
  '교통체증',
  '빚',
  '프렌',
  '차',
  '이즈',
  '커피전문점',
  '관계자',
  '빵',
  '커피',
  '우리',
  '안',
  '제과점',
  '게',
  '말',
  '고',
  '불만',
  '토로'],
 [],
 ['방역',
  '강화',
  '명',
  '이상',
  '규모',
  '현장',
  '결혼식',
  '원천',
  '봉쇄',
  '온라인',
  '결혼식',
  '방향',
  '선회',
  '부부',
  '늘',
  '예식',
  '차례',
  '연기',
  '신준하',
  '김지현',
  '부부',
  '최근',
  '코로나',
  '재',
  '확산',
  '하자',
  '오프라인',
  '결혼식',
  '포기',
  '온라인',
  '결혼식',
  '이',
  '모바일',
  '청첩장',
  '결혼식',
  '영상',
  '중계',
  '홈페이지',
  '주소',
  '첨부',
  '지인'],
 [],
 ['오후',
  '생중계',
  '이',
  '결혼식',
  '명',
  '온라인',
  '하객',
  '이',
  '신부',
  '아버지',
  '직접',
  '축가',
  '하자',
  '아버님',
  '축가',
  '댓글',
  '달리기',
  '신씨',
  '이번',
  '사태',
  '계기',
  '결혼식',
  '문화',
  '수',
  '생각',
  '고',
  '말',
  '대만',
  '여성',
  '한국',
  '결혼식',
  '김모',
  '씨',
  '온라인',
  '생중계',
  '코로나',
  '재',
  '확산',
  '대만',
  '신부',
  '부모',
  '참석',
  '때문'],
 [],
 ['온라인',
  '결혼식',
  '중계',
  '이준희',
  '가빈',
  '컴퍼니',
  '대표',
  '온라인',
  '하객',
  '은',
  '계좌',
  '번호',
  '링크',
  '형태',
  '전달',
  '축의금',
  '수',
  '혼주',
  '쪽',
  '하객',
  '입력',
  '주소',
  '전화번호',
  '이용',
  '답례',
  '품',
  '수',
  '며',
  '지난',
  '하객',
  '수',
  '제한',
  '조처',
  '이후',
  '건',
  '문의',
  '고',
  '말',
  '한편',
  '질병',
  '관리',
  '본부',
  '중앙',
  '방역',
  '대책',
  '본부',
  '방',
  '대본',
  '기준',
  '전국',
  '코로나',
  '환자',
  '하루',
  '동안',
  '명',
  '지난',
  '명',
  '이후',
  '닷새',
  '명',
  '아래',
  '정은경',
  '방대',
  '본부장',
  '코로나',
  '최후',
  '방어선',
  '생각',
  '의료',
  '기관',
  '시설',
  '확산',
  '중이',
  '역학',
  '조사',
  '여력',
  '한계',
  '상황',
  '라며',
  '코로나',
  '를',
  '다시',
  '통제',
  '수준',
  '수',
  '판가름',
  '시기',
  '만큼',
  '거리',
  '두기',
  '이행',
  '달라',
  '고',
  '말'],
 [],
 ['정진호', '채혜선', '권', '혜림', '민정', '기자'],
 [],
 [],
 [],
 [],
 [],
 [],
 ['중앙', '일보', '무단', '재', '및', '재', '배포', '금지']]

In [24]:
# 빈줄 삭제
last_nouns=[i for i in last_nouns if len(i) !=0]
len(last_nouns)
last_nouns # 각 문서에서 명사 추출

[['밤', '수도권', '대상', '사회', '거리', '두기', '시행', '음식점', '등', '오후', '대거', '문', '때문'],
 ['시행',
  '첫날',
  '날',
  '중심',
  '가의',
  '식당',
  '술집',
  '등',
  '매장',
  '내',
  '취식',
  '금지',
  '시작',
  '시각',
  '오후',
  '전후',
  '장사',
  '한식',
  '집',
  '등',
  '식사',
  '위주',
  '식당',
  '해',
  '지면',
  '찌',
  '감치',
  '마감',
  '고깃집',
  '횟집',
  '이자카야',
  '맥줏집',
  '등',
  '데드라인',
  '이',
  '임박',
  '손님',
  '매장',
  '정리',
  '시작',
  '평소',
  '라면',
  '간판',
  '불빛',
  '불야성',
  '번화가',
  '골목',
  '깜깜',
  '정도'],
 ['종각역',
  '인근',
  '맥줏집',
  '사장',
  '김모',
  '씨',
  '오후',
  '손님',
  '오후',
  '마감',
  '달라',
  '고',
  '부탁',
  '이',
  '가게',
  '평소',
  '영업',
  '시간',
  '오후',
  '다음',
  '날',
  '오전',
  '김씨',
  '원래',
  '가장',
  '시간',
  '문',
  '코로나',
  '때문',
  '매출',
  '액',
  '예년',
  '로',
  '젠',
  '그',
  '반토막',
  '안',
  '것',
  '고',
  '한숨'],
 ['오후',
  '식당',
  '최모',
  '씨',
  '친구',
  '약속',
  '때문',
  '강제',
  '이',
  '시간',
  '귀가',
  '고',
  '말',
  '층',
  '규모',
  '대형',
  '술집',
  '시행',
  '다음',
  '달',
  '아예',
  '문',
  '이',
  '술집',
  '사장',
  '오후',
  '영업',
  '건',
  '그냥',
  '술집',
  '문',
  '이야기',
  '라며',
  '포장',
  '배달',
  '누가',
  '술집',
  '술',
  '안주',
  '배달',
  '말',
  '서울역',
  '대합실',
  '내',
  '한식당',
  '등',
  '오후',
  '이전',
  '문',
  '패스트푸드',
  '가게',
  '일부',
  '포장',
  '주문',
  '손님',
  '눈',
  '뿐'],
 ['중구',
  '국집',
  '사장',
  '홍',
  '정복',
  '씨',
  '원래',
  '오후',
  '오전',
  '사이',
  '매출',
  '전체',
  '를',
  '차지',
  '며',
  '매출',
  '액',
  '동참',
  '최대한',
  '코로나',
  '고',
  '말'],
 ['업종',
  '별로',
  '희비',
  '갈리',
  '기도',
  '온종일',
  '포장',
  '배달',
  '판매',
  '프랜차이즈',
  '커피전문점',
  '모습'],
 ['결혼식', '온라인', '생중계', '축하', '댓글', '축의금', '계좌', '이체'],
 ['오후',
  '정자동',
  '카페',
  '거리',
  '로',
  '경기도',
  '성남시',
  '분당구',
  '정자동',
  '카페',
  '밀집',
  '지역',
  '스타벅스',
  '고객',
  '고객',
  '발길',
  '일쑤',
  '매장',
  '직원',
  '포장',
  '판매',
  '설명',
  '발길',
  '고객',
  '명',
  '이상',
  '화',
  '고객',
  '며',
  '한숨'],
 ['곳',
  '불과',
  '파리',
  '바게뜨',
  '별천지',
  '인석',
  '테이블',
  '개',
  '중',
  '개',
  '손님',
  '이',
  '가족',
  '지인',
  '커피',
  '빵',
  '노트북',
  '컴퓨터',
  '이용',
  '개인',
  '업무',
  '이도',
  '제과점',
  '음식점',
  '마찬가지',
  '오전',
  '오후',
  '현장',
  '취식',
  '때문',
  '또',
  '다른',
  '무풍지대',
  '인',
  '비',
  '프랜차이즈',
  '소규모',
  '개인',
  '카페',
  '고객',
  '북적',
  '소셜네트워크서비스',
  '인기',
  '끌',
  '경기도',
  '광주시',
  '카페',
  '낮',
  '수용',
  '수',
  '층',
  '주차장',
  '차',
  '상태'],
 ['프랜차이즈',
  '커피전문점',
  '중',
  '차',
  '안',
  '음료',
  '드라이브',
  '스루',
  '방식',
  '매장',
  '현장',
  '취식',
  '금지',
  '대상',
  '고객',
  '발길',
  '낮',
  '경기도',
  '남양주시',
  '스타벅스',
  '드라이브',
  '스루',
  '점포',
  '차로',
  '차량',
  '대가',
  '줄줄이',
  '송파',
  '나루',
  '역',
  '인근',
  '매장',
  '고객',
  '차량',
  '나',
  '줄',
  '바람',
  '교통체증',
  '빚',
  '프렌',
  '차',
  '이즈',
  '커피전문점',
  '관계자',
  '빵',
  '커피',
  '우리',
  '안',
  '제과점',
  '게',
  '말',
  '고',
  '불만',
  '토로'],
 ['방역',
  '강화',
  '명',
  '이상',
  '규모',
  '현장',
  '결혼식',
  '원천',
  '봉쇄',
  '온라인',
  '결혼식',
  '방향',
  '선회',
  '부부',
  '늘',
  '예식',
  '차례',
  '연기',
  '신준하',
  '김지현',
  '부부',
  '최근',
  '코로나',
  '재',
  '확산',
  '하자',
  '오프라인',
  '결혼식',
  '포기',
  '온라인',
  '결혼식',
  '이',
  '모바일',
  '청첩장',
  '결혼식',
  '영상',
  '중계',
  '홈페이지',
  '주소',
  '첨부',
  '지인'],
 ['오후',
  '생중계',
  '이',
  '결혼식',
  '명',
  '온라인',
  '하객',
  '이',
  '신부',
  '아버지',
  '직접',
  '축가',
  '하자',
  '아버님',
  '축가',
  '댓글',
  '달리기',
  '신씨',
  '이번',
  '사태',
  '계기',
  '결혼식',
  '문화',
  '수',
  '생각',
  '고',
  '말',
  '대만',
  '여성',
  '한국',
  '결혼식',
  '김모',
  '씨',
  '온라인',
  '생중계',
  '코로나',
  '재',
  '확산',
  '대만',
  '신부',
  '부모',
  '참석',
  '때문'],
 ['온라인',
  '결혼식',
  '중계',
  '이준희',
  '가빈',
  '컴퍼니',
  '대표',
  '온라인',
  '하객',
  '은',
  '계좌',
  '번호',
  '링크',
  '형태',
  '전달',
  '축의금',
  '수',
  '혼주',
  '쪽',
  '하객',
  '입력',
  '주소',
  '전화번호',
  '이용',
  '답례',
  '품',
  '수',
  '며',
  '지난',
  '하객',
  '수',
  '제한',
  '조처',
  '이후',
  '건',
  '문의',
  '고',
  '말',
  '한편',
  '질병',
  '관리',
  '본부',
  '중앙',
  '방역',
  '대책',
  '본부',
  '방',
  '대본',
  '기준',
  '전국',
  '코로나',
  '환자',
  '하루',
  '동안',
  '명',
  '지난',
  '명',
  '이후',
  '닷새',
  '명',
  '아래',
  '정은경',
  '방대',
  '본부장',
  '코로나',
  '최후',
  '방어선',
  '생각',
  '의료',
  '기관',
  '시설',
  '확산',
  '중이',
  '역학',
  '조사',
  '여력',
  '한계',
  '상황',
  '라며',
  '코로나',
  '를',
  '다시',
  '통제',
  '수준',
  '수',
  '판가름',
  '시기',
  '만큼',
  '거리',
  '두기',
  '이행',
  '달라',
  '고',
  '말'],
 ['정진호', '채혜선', '권', '혜림', '민정', '기자'],
 ['중앙', '일보', '무단', '재', '및', '재', '배포', '금지']]

In [26]:
# 단어 집합
word_list=sorted(list(set([j for i in last_nouns for j in i])))
print(len(word_list))
word_list

329

['가게',
 '가빈',
 '가의',
 '가장',
 '가족',
 '간판',
 '갈리',
 '감치',
 '강제',
 '강화',
 '개',
 '개인',
 '거리',
 '건',
 '것',
 '게',
 '결혼식',
 '경기도',
 '계기',
 '계좌',
 '고',
 '고객',
 '고깃집',
 '골목',
 '곳',
 '관계자',
 '관리',
 '광주시',
 '교통체증',
 '국집',
 '권',
 '귀가',
 '규모',
 '그',
 '그냥',
 '금지',
 '기관',
 '기도',
 '기자',
 '기준',
 '김모',
 '김씨',
 '김지현',
 '깜깜',
 '끌',
 '나',
 '나루',
 '날',
 '남양주시',
 '낮',
 '내',
 '노트북',
 '누가',
 '눈',
 '늘',
 '다른',
 '다시',
 '다음',
 '달',
 '달라',
 '달리기',
 '답례',
 '닷새',
 '대가',
 '대거',
 '대만',
 '대본',
 '대상',
 '대책',
 '대표',
 '대합실',
 '대형',
 '댓글',
 '데드라인',
 '동안',
 '동참',
 '두기',
 '드라이브',
 '등',
 '때문',
 '또',
 '라며',
 '라면',
 '로',
 '를',
 '링크',
 '마감',
 '마찬가지',
 '만큼',
 '말',
 '매장',
 '매출',
 '맥줏집',
 '며',
 '명',
 '모바일',
 '모습',
 '무단',
 '무풍지대',
 '문',
 '문의',
 '문화',
 '민정',
 '밀집',
 '및',
 '바게뜨',
 '바람',
 '반토막',
 '발길',
 '밤',
 '방',
 '방대',
 '방식',
 '방어선',
 '방역',
 '방향',
 '배달',
 '배포',
 '번호',
 '번화가',
 '별로',
 '별천지',
 '본부',
 '본부장',
 '봉쇄',
 '부모',
 '부부',
 '부탁',
 '북적',
 '분당구',
 '불과',
 '불만',
 '불빛',
 '불야성',
 '비',
 '빚',
 '빵',
 '뿐',
 '사이',
 '사장',
 '사태',
 '사회',
 '상태',
 '상황',
 '생각',
 '생중계',
 '서울역',
 '선회',
 '설명',
 '성남시',
 '소규모',
 '소셜네트워크서비스',
 '손님',
 '송파',
 '수',
 '수도권',
 '수용',
 '수준',
 '술',
 '술집',
 '스루',
 '스타벅스',
 '시각',
 '시간',
 '시기',
 '시설',
 '시작',
 '시행',
 '식당',
 '식사',
 '신부',
 '신씨',
 '신준하',
 '씨',
 '아래',
 '아버님',
 '아버지',
 '아예',
 '안',
 '안주',
 '액',
 '약속',
 '업무',
 '업종',
 '여력',
 '여성',
 '역',
 '역학',
 '연기',
 '영상',
 '영업',
 '예년',
 '예식',
 '오전',
 '오프라인',
 '오후',
 '온라인',
 '온종일',
 '우리',
 '원래',
 '원천',
 '위주',
 '은',
 '음료',
 '음식점',
 '의료',
 '이',
 '이도',
 '이번',
 '이상',
 '이야기',
 '이용',
 '이자카야',
 '이전',
 '이준희',
 '이즈',
 '이체',
 '이행',
 '이후',
 '인',
 '인근',
 '인기',
 '인석',
 '일보',
 '일부',
 '일쑤',
 '임박',
 '입력',
 '장사',
 '재',
 '전국',
 '전달',
 '전체',
 '전화번호',
 '전후',
 '점포',
 '정도',
 '정리',
 '정복',
 '정은경',
 '정자동',
 '정진호',
 '제과점',
 '제한',
 '젠',
 '조사',
 '조처',
 '종각역',
 '주문',
 '주소',
 '주차장',
 '줄',
 '줄줄이',
 '중',
 '중계',
 '중구',
 '중심',
 '중앙',
 '중이',
 '지난',
 '지면',
 '지역',
 '지인',
 '직원',
 '직접',
 '질병',
 '집',
 '쪽',
 '찌',
 '차',
 '차량',
 '차례',
 '차로',
 '차지',
 '참석',
 '채혜선',
 '첨부',
 '첫날',
 '청첩장',
 '최근',
 '최대한',
 '최모',
 '최후',
 '축가',
 '축의금',
 '축하',
 '취식',
 '층',
 '친구',
 '카페',
 '커피',
 '커피전문점',
 '컴퍼니',
 '컴퓨터',
 '코로나',
 '테이블',
 '토로',
 '통제',
 '파리',
 '판가름',
 '판매',
 '패스트푸드',
 '평소',
 '포기',
 '포장',
 '품',
 '프랜차이즈',
 '프렌',
 '하객',
 '하루',
 '하자',
 '한계',
 '한국',
 '한숨',
 '한식',
 '한식당',
 '한편',
 '해',
 '현장',
 '형태',
 '혜림',
 '혼주',
 '홈페이지',
 '홍',
 '화',
 '확산',
 '환자',
 '횟집',
 '희비']

In [30]:
count=[]
for i in last_nouns:
    count.append([])
    for j in word_list:
        count[-1].append(i.count(j))
tf_df=pd.DataFrame(count,columns=word_list)
tf_df

,가게,가빈,가의,가장,가족,간판,갈리,감치,강제,강화,...,형태,혜림,혼주,홈페이지,홍,화,확산,환자,횟집,희비
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,1,0,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
2,1,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
5,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
8,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,1,...,0,0,0,1,0,0,1,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
12,0,1,0,0,0,0,0,0,0,0,...,1,0,1,0,0,0,1,1,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [27]:
['가','가','나'].count('가')

2

In [28]:
'가 가 나 '.count('가')

2

In [37]:
# idf
D=len(tf_df)
# print(D)
df=tf_df.astype('bool').sum()
# df
idf=np.log(D/(df+1))
tfidf_df=tf_df*idf
tfidf_df

,가게,가빈,가의,가장,가족,간판,갈리,감치,강제,강화,...,형태,혜림,혼주,홈페이지,홍,화,확산,환자,횟집,희비
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.000000,0.000000,2.014903,0.000000,0.000000,2.014903,0.000000,2.014903,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.014903,0.000000
2,1.609438,0.000000,0.000000,2.014903,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,1.609438,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.014903,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,2.014903,0.000000,0.000000,0.000000,0.000000,0.000000
5,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.014903,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.014903
6,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,2.014903,0.000000,0.000000,0.000000,0.000000
8,0.000000,0.000000,0.000000,0.000000,2.014903,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.014903,...,0.000000,0.000000,0.000000,2.014903,0.000000,0.000000,1.321756,0.000000,0.000000,0.000000
11,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.321756,0.000000,0.000000,0.000000
12,0.000000,2.014903,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,2.014903,0.000000,2.014903,0.000000,0.000000,0.000000,1.321756,2.014903,0.000000,0.000000
13,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,2.014903,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [40]:
from sklearn.metrics.pairwise import cosine_similarity
cos_sim = cosine_similarity(tfidf_df,tfidf_df)
result_df = pd.DataFrame(cos_sim)
result_df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,1.000000,0.093863,0.058619,0.127114,0.005773,0.000000,0.000000,0.032280,0.046834,0.031068,0.000000,0.015661,0.039265,0.0,0.000000
1,0.093863,1.000000,0.093506,0.144207,0.002400,0.000000,0.000000,0.025089,0.020019,0.052254,0.003430,0.008414,0.000000,0.0,0.024411
2,0.058619,0.093506,1.000000,0.190970,0.220501,0.000000,0.000000,0.053535,0.036545,0.059829,0.011268,0.068205,0.037574,0.0,0.000000
3,0.127114,0.144207,0.190970,1.000000,0.052268,0.095747,0.000000,0.027085,0.032899,0.010678,0.020997,0.041556,0.034594,0.0,0.000000
4,0.005773,0.002400,0.220501,0.052268,1.000000,0.000000,0.000000,0.022925,0.018096,0.012100,0.008471,0.037677,0.062345,0.0,0.000000
5,0.000000,0.000000,0.000000,0.095747,0.000000,1.000000,0.000000,0.062710,0.019938,0.074728,0.000000,0.000000,0.000000,0.0,0.000000
6,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.148756,0.243504,0.098755,0.0,0.000000
7,0.032280,0.025089,0.053535,0.027085,0.022925,0.062710,0.000000,1.000000,0.126751,0.167034,0.027835,0.010779,0.033237,0.0,0.000000
8,0.046834,0.020019,0.036545,0.032899,0.018096,0.019938,0.000000,0.126751,1.000000,0.139790,0.028458,0.023239,0.035319,0.0,0.000000
9,0.031068,0.052254,0.059829,0.010678,0.012100,0.074728,0.000000,0.167034,0.139790,1.000000,0.009555,0.007782,0.009901,0.0,0.022612
10,0.000000,0.003430,0.011268,0.020997,0.008471,0.000000,0.148756,0.027835,0.028458,0.009555,1.000000,0.209105,0.109473,0.0,0.053563
11,0.015661,0.008414,0.068205,0.041556,0.037677,0.000000,0.243504,0.010779,0.023239,0.007782,0.209105,1.000000,0.151039,0.0,0.053657
12,0.039265,0.000000,0.037574,0.034594,0.062345,0.000000,0.098755,0.033237,0.035319,0.009901,0.109473,0.151039,1.000000,0.0,0.025304
13,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,0.000000
14,0.000000,0.024411,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.022612,0.053563,0.053657,0.025304,0.0,1.000000

In [41]:
tfidf_df

,가게,가빈,가의,가장,가족,간판,갈리,감치,강제,강화,...,형태,혜림,혼주,홈페이지,홍,화,확산,환자,횟집,희비
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.000000,0.000000,2.014903,0.000000,0.000000,2.014903,0.000000,2.014903,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.014903,0.000000
2,1.609438,0.000000,0.000000,2.014903,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
3,1.609438,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.014903,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,2.014903,0.000000,0.000000,0.000000,0.000000,0.000000
5,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.014903,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.014903
6,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,2.014903,0.000000,0.000000,0.000000,0.000000
8,0.000000,0.000000,0.000000,0.000000,2.014903,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.014903,...,0.000000,0.000000,0.000000,2.014903,0.000000,0.000000,1.321756,0.000000,0.000000,0.000000
11,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.321756,0.000000,0.000000,0.000000
12,0.000000,2.014903,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,2.014903,0.000000,2.014903,0.000000,0.000000,0.000000,1.321756,2.014903,0.000000,0.000000
13,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,2.014903,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
14,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [45]:
tfidf_df.corr()['코로나'].sort_values(ascending=False)

코로나      1.000000
하객       0.872230
명        0.848296
컴퍼니      0.840511
관리       0.840511
           ...
경기도     -0.289662
시행      -0.289662
금지      -0.289662
프랜차이즈   -0.289662
취식      -0.289662
Name: 코로나, Length: 329, dtype: float64

In [47]:
result_df[0].sort_values(ascending=False)

0     1.000000
3     0.127114
1     0.093863
2     0.058619
8     0.046834
12    0.039265
7     0.032280
9     0.031068
11    0.015661
4     0.005773
5     0.000000
6     0.000000
10    0.000000
13    0.000000
14    0.000000
Name: 0, dtype: float64

In [49]:
print(' '.join(last_nouns[0]))
print('----------------------')
print(' '.join(last_nouns[3]))

밤 수도권 대상 사회 거리 두기 시행 음식점 등 오후 대거 문 때문
----------------------
오후 식당 최모 씨 친구 약속 때문 강제 이 시간 귀가 고 말 층 규모 대형 술집 시행 다음 달 아예 문 이 술집 사장 오후 영업 건 그냥 술집 문 이야기 라며 포장 배달 누가 술집 술 안주 배달 말 서울역 대합실 내 한식당 등 오후 이전 문 패스트푸드 가게 일부 포장 주문 손님 눈 뿐