In [74]:
import numpy as np
import pandas as pd

In [75]:
txt={'파이썬 차트 파이썬 머신러닝',
    '차트 파이썬 R 차트',
    'R 분석 시각화'}

In [76]:
txtList=[i.split() for i in txt]
txtList

[['파이썬', '차트', '파이썬', '머신러닝'], ['차트', '파이썬', 'R', '차트'], ['R', '분석', '시각화']]

In [73]:
# 문서 전체에 등장하는 단어들 추출
nouns=sorted(list(set([j for i in txtList for j in i])))
nouns

['R', '머신러닝', '분석', '시각화', '차트', '파이썬']

In [80]:
dtm=[]
for i in txtList:
    dtm.append([])
    for j in nouns:
        dtm[-1].append(i.count(j))
tf=pd.DataFrame(dtm,columns=nouns)
tf

   R  머신러닝  분석  시각화  차트  파이썬
0  0     1   0    0   1    2
1  1     0   0    0   2    1
2  1     0   1    1   0    0

In [85]:
D=len(tf)
df=tf.astype('bool').sum()
idf=D/df
idf

R       1.5
머신러닝    3.0
분석      3.0
시각화     3.0
차트      1.5
파이썬     1.5
dtype: float64

In [79]:
a=[3,4,0,5,1] # [1,1,0,1,1]
[bool(i) for i in a]

[True, True, False, True, True]

In [88]:
#TF-IDF
tfidf=tf*idf
tfidf

     R  머신러닝   분석  시각화   차트  파이썬
0  0.0   3.0  0.0  0.0  1.5  3.0
1  1.5   0.0  0.0  0.0  3.0  1.5
2  1.5   0.0  3.0  3.0  0.0  0.0

In [89]:
tf

   R  머신러닝  분석  시각화  차트  파이썬
0  0     1   0    0   1    2
1  1     0   0    0   2    1
2  1     0   1    1   0    0

In [93]:
!pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.5.2-cp312-cp312-win_amd64.whl.metadata (13 kB)
Requirement already satisfied: numpy>=1.19.5 in c:\users\human\.conda\envs\edu\lib\site-packages (from scikit-learn) (2.1.1)
Collecting scipy>=1.6.0 (from scikit-learn)
  Downloading scipy-1.14.1-cp312-cp312-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.2.0 (from scikit-learn)
  Downloading joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn)
  Downloading threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.5.2-cp312-cp312-win_amd64.whl (11.0 MB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   -------- ------------------------------- 2.4/11.0 MB 12.2 MB/s eta 0:00:01
   ----------- ---------------------------- 3.1/11.0 MB 12.3 MB/s eta 0:00:01
   ---------------- ----------------------- 4.5/11.0 MB 6.9 MB/s eta 0:00:01
   ------------------------ --------------- 6.8/11.0 MB 8.1 MB/s eta 0:00:01
   --------------------------------- ------ 9.2/11.0 MB 8.8 MB/s eta 0:00:01
   ---------------------------------------  10.7/11.0 MB 9.2 MB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 8.2 MB/s eta 0:00:00
Downloading joblib-1.4.2-py3-none-any.whl (301 kB)
Downloading scipy-1.14.1-cp312-cp312-win_amd64.whl (44.5 MB)
   ---------------------------------------- 0.0/44.5 MB ? eta -:--:--
   -- ------------------------------------- 2.4/44.5 MB 11.2 MB/s eta 0:00:04
   ---- ----------------------------------- 4.7/44.5 MB 11.9 MB/s eta 0:00:04
   ------ --------------------------------- 7.1/44.5 MB 11.8 MB/s eta 0:00:04
   ------- -------------------------------- 8.4/44.5 MB 11.5 MB/s eta 0:00:04
   -------- ------------------------------- 9.2/44.5 MB 8.8 MB/s eta 0:00:05
   ---------- ----------------------------- 11.5/44.5 MB 9.2 MB/s eta 0:00:04
   ------------ --------------------------- 14.2/44.5 MB 9.7 MB/s eta 0:00:04
   -------------- ------------------------- 16.5/44.5 MB 9.9 MB/s eta 0:00:03
   ---------------- ----------------------- 18.9/44.5 MB 10.1 MB/s eta 0:00:03
   ------------------ --------------------- 21.0/44.5 MB 10.2 MB/s eta 0:00:03
   -------------------- ------------------- 22.3/44.5 MB 9.7 MB/s eta 0:00:03
   --------------------- ------------------ 24.1/44.5 MB 9.8 MB/s eta 0:00:03
   ----------------------- ---------------- 26.2/44.5 MB 9.8 MB/s eta 0:00:02
   ------------------------- -------------- 28.8/44.5 MB 9.9 MB/s eta 0:00:02
   ---------------------------- ----------- 31.2/44.5 MB 10.0 MB/s eta 0:00:02
   ------------------------------ --------- 33.6/44.5 MB 10.1 MB/s eta 0:00:02
   -------------------------------- ------- 35.9/44.5 MB 10.2 MB/s eta 0:00:01
   --------------------------------- ------ 37.7/44.5 MB 10.3 MB/s eta 0:00:01
   ----------------------------------- ---- 39.3/44.5 MB 10.0 MB/s eta 0:00:01
   ------------------------------------- -- 41.9/44.5 MB 10.1 MB/s eta 0:00:01
   ---------------------------------------  44.3/44.5 MB 10.2 MB/s eta 0:00:01
   ---------------------------------------  44.3/44.5 MB 10.2 MB/s eta 0:00:01
   ---------------------------------------- 44.5/44.5 MB 9.6 MB/s eta 0:00:00
Downloading threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
Successfully installed joblib-1.4.2 scikit-learn-1.5.2 scipy-1.14.1 threadpoolctl-3.5.0

In [98]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [99]:
tfidf_vectorizer=TfidfVectorizer()
tfidf_vectorizer.fit_transform(txt)
tfidf_vectorizer

TfidfVectorizer()

In [100]:
tfidf_feature=tfidf_vectorizer.get_feature_names_out()
tfidf_feature

array(['머신러닝', '분석', '시각화', '차트', '파이썬'], dtype=object)

In [106]:
tfidf_matrix=tfidf_vectorizer.fit_transform(txt)
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 7 stored elements and shape (3, 5)>

In [107]:
tfidf_=pd.DataFrame(tfidf_matrix.toarray(),columns=tfidf_feature)
tfidf_

      머신러닝        분석       시각화        차트       파이썬
0  0.50689  0.000000  0.000000  0.385503  0.771006
1  0.00000  0.000000  0.000000  0.894427  0.447214
2  0.00000  0.707107  0.707107  0.000000  0.000000